---

- name: Change apt source file content
  lineinfile:
    dest: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^deb.?', line: "deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/debian {{ ansible_distribution_release }} main" }
    - { regexp: '^deb-src.?', line: "deb-src https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/debian {{ ansible_distribution_release }} main" }
      
      
