---
- name: Add Gitlab gpg key
  apt_key:
    url: "https://packages.gitlab.com/gpg.key"

- name: Change apt source file content
  apt_repository:
     repo: "deb https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/{{ ansible_distribution.lower() }}  {{ ansible_distribution_release }} main"
     state: present
     filename: "gitlab-ce"

- name: Update repository
  apt:
    update_cache: yes
  
