---

- name: Change apt source file content
  template:
    src: debian_tuna_apt_source.j2
    dest: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
    owner: root
    group: root
      

- name: Update repository
  apt:
    update_cache: yes
  
