---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_ctl

# Install GitLab dependencies.
- name: Install GitLab dependencies.
  package: name={{ item }} state=installed
  with_items:
    - openssh-server
    - postfix
    - curl

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
  when: gitlab_ctl.stat.exists == false

- name: Install GitLab repository
  command: bash /tmp/gitlab_install_repository.sh
  when: gitlab_ctl.stat.exists == false

- name: Include distribution task.
  include: "{{ ansible_os_family }}.yml"
  when: gitlab_tuna_mirrors

- name: Install GitLab
  package: name=gitlab-ce state=installed
  when: gitlab_ctl.stat.exists == false

- name: Copy GitLab configuration file.
  template:
    src: gitlab_config.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root

- name: Reconfigure Gitlab
  command: >
    gitlab-ctl reconfigure

- name: Restart Gitlab
  command: >
    gitlab-ctl restart
